# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-13 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
import model_utils.fields
import sport_chat.chats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('soon', 'Soon'), ('online', 'Online'), ('end', 'End')], default='soon', max_length=20)),
                ('name', models.CharField(max_length=55, verbose_name='Name of event')),
                ('start_date', models.DateTimeField(help_text='Date and time when the event should start', verbose_name='Start date and time')),
                ('end_date', models.DateTimeField(help_text='Date and time when the event should end', verbose_name='End date and time')),
                ('started_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when=set(['online']))),
                ('ended_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when=set(['end']))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=255)),
                ('every', models.PositiveSmallIntegerField(default=0, help_text='The message will be sent each N number of minutes', verbose_name='Every')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=55, verbose_name='Name of team')),
                ('flag', models.ImageField(upload_to=sport_chat.chats.models.team_flag_directory_path)),
                ('cropping', image_cropping.fields.ImageRatioField('flag', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='team_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_team_left', to='chats.Team', verbose_name='Left team'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_team_right', to='chats.Team', verbose_name='Right team'),
        ),
    ]
