# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-23 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
