# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Team'),
        ),
    ]
