# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20171026_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MESSAGE'), (1, 'WARNING'), (2, 'ALERT'), (3, 'MUTED'), (4, 'ENTER'), (5, 'LEAVE')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='team_type',
            field=models.CharField(choices=[('home', 'Home'), ('away', 'Away')], default='home', max_length=4),
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_messages', to='chats.Event'),
        ),
        migrations.AlterField(
            model_name='message',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_messages', to='chats.Team'),
        ),
    ]
