# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 18:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
