# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 19:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20171028_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
